name: Deployment issue
description: Report an issue with a deployment
title: "[Deployment]: <title>"
labels: ["deployment"]
projects: ["SE-UUlm/2"]

body:
    - type: checkboxes
      id: existing-issue
      attributes:
          label: Is there an existing issue for this?
          description: Please check whether this issue has already been reported.
          options:
              - label: I have searched the existing issues
                required: true

    - type: dropdown
      id: environment
      attributes:
          label: Environment
          description: Which environment is affected?
          options:
              - Development
              - Production
      validations:
          required: true

    - type: input
      id: version
      attributes:
          label: Version/Commit
          description: Which version or commit is deployed?
          placeholder: e.g. "v1.2.3" or "a1b2c3d"
      validations:
          required: true

    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: A clear and concise description of what the issue is.
          placeholder: e.g. "The login is not working after the latest deployment."
      validations:
          required: true

    - type: textarea
      id: logs
      attributes:
          label: Deployment Logs & Artifacts
          description: Please provide relevant logs and/or artifacts from the deployment.
          placeholder: |
              <details>
              <summary>Click to expand</summary>

              ```
              ...
              ```

              </details>
      validations:
          required: false

    - type: textarea
      id: impact
      attributes:
          label: Impact
          description: What is the impact of this issue?
          placeholder: e.g. "Users are not able to log in."
      validations:
          required: false

    - type: textarea
      id: additional-context
      attributes:
          label: Anything else?
          description: |
              Screenshots, links, or any other context that helps us debug the issue.

              Tip: You can drag and drop files here.
      validations:
          required: false
