name: Deploy Development

on:
  workflow_dispatch:
  schedule:
    -   cron: "0 5 * * *" # Every night at 05:00 AM
  push:
    branches: [ "main" ]

jobs:
  snowballr-deploy-dev:
    uses: ./.github/workflows/deploy.yml
    with:
      profile: development
